### ISSUE TITLE
new logo for the project

### ISSUE THREAD

**Issue by nightsoundars** [nearmap/kcd#33]
Hello! I want to contribute on your project with making logo design. What do you think about it?

**Comment by suneeta-mall** [comment]
@nightsoundars Thanks a lot for raising the issue request. You are absolutely right that we need a logo and mascot for the project. We are rejigging a few things on the project and logo and mascot are a part of that. 
We appreciate your interest and certainly welcome contributions. But the logo and mascots are already WIP internally.

**Comment by Waynetron** [comment]
Not sure where you want these files to live. So I'll just include them here.
[kcd logo.zip](https://github.com/nearmap/kcd/files/2239710/kcd.logo.zip)
